//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteEndereco
    {
        public int id { get; set; }
        public int idCliente { get; set; }
        public string TipoEndereco { get; set; }
        public string Logradouro { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string CIdade { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string CEP { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
