//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.ClienteEndereco = new HashSet<ClienteEndereco>();
        }
    
        public int id { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> Nascimento { get; set; }
        public string Senha { get; set; }
        public string CPF { get; set; }
    
        public virtual ICollection<ClienteEndereco> ClienteEndereco { get; set; }
    }
}
