//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.Preco = new HashSet<Preco>();
        }
    
        public int id { get; set; }
        public string DescrCurta { get; set; }
        public string DescrDetalhada { get; set; }
        public string Informacoes { get; set; }
    
        public virtual ICollection<Preco> Preco { get; set; }
    }
}
